// Generated by https://quicktype.io

export interface ProductResponse {
  product: Product[];
}

export interface Product {
  category: string;
  price: string;
  stocked: boolean;
  name: string;
}
